### ISSUE TITLE
As a data modeler, define the schema for the following tables:

### ISSUE THREAD

**Issue by zenglenn42** [greenleavesbyroot/greenleaves#25]
- [x] products
- [x] customers
- [ ] admin users
- [x] orders
- [x] product categories
- [ ] access rights

**Comment by golemheavy** [comment]
for MVP, we are defining each product having exactly one category.

So, we don't need a separate table for product categories. We just must have a non-nullable category field, and we can use the data type "enum" to enumerate the possibilities for this column.

**Comment by zenglenn42** [comment]
The work was addressed over several commits.  A roll-up of that work is available by inspecting this Phase 1 development file:

https://github.com/greenleavesbyroot/greenleaves/blob/1dfa0c066c58e5274e17887967c431169a19fd14/controllers/api/api-routes.js#L17
