### ISSUE TITLE
As a react developer, define the high-level frontend app components and file structure.

### ISSUE THREAD

**Issue by zenglenn42** [greenleavesbyroot/greenleaves#29]
We need /some/ structure to all our react components.  

This may evolve as we get smarter about:

smart components that
  * manage state
  * load data from data endpoints
  * define handlers for user interface elements

render-only components
  * take in props and state and render stuff

**Comment by zenglenn42** [comment]
This is my initial thinking:

```repobase/client/src/components/

    Admin
        Products   (crud)
        Categories (crud)
        Orders     (-rud) (created by shopping)
        Customers  (crud)

    App 
        About
        Browse (-r--) read products table

    Login
        Profile    (crud)

    Customer
        Shop       (browse with add-to-cart)
        Cart       (crud)  creates order
        Orders     (-rud)
```

**Comment by tuequach** [comment]
made a PR based on your model. thanks for clarifying
